site_name: OpenBreather Documentation
site_url: https://sitename.example
theme:
  name: material
  font: 
    text: Metrophobic
    code: Red Hat Text
  icon:
    logo: material/chart-bubble
  # favicon: material/chart-bubble
  # features:
  #   - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
