site_name: OpenBreather 
site_url: https://sitename.example
theme:
  name: material
  font: 
    text: Rubik
    code: Red Hat Text
  icon:
    logo: material/chart-bubble
  # favicon: material/chart-bubble
  # features:
  #   - navigation.footer
  palette: 
    scheme: default
    primary: yellow
    accent: blue

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      toc_depth: 0
  - pymdownx.arithmatex:
      generic: true


plugins:
    # - search: {}
    - encryptcontent:
        global_password: 'test'
        encrypted_something:
          md-sidebar--primary: [div, class]   # Encrypts the Left Sidebar (Site Navigation)
        summary: 'Encrypted content'
        encryption_info_message: 'Please enter the password to view.'

extra_css:
  - stylesheets/extra.css

nav:  
  - Warning!: index.md
  - What is OpenBreather?: what_is_openbreather.md
  - How to contribute: how_to_contribute.md
  - Glossary: glossary.md
  - Complete designs:
    - Guppy Pendulum CCR: 
      - Design brief: guppy_ccr/design_brief.md
      - Analysis: 
        - Design for manufacturing: guppy_ccr/analysis/design_for_manufacturing.md
        - Scrubber bedlife: guppy_ccr/analysis/scrubber_bedlife.md
        - Work of breathing: guppy_ccr/analysis/work_of_breathing.md
      - Assembly: guppy_ccr/assembly.md
      - Performance: guppy_ccr/performance.md

  - Appendix: appendix.md



extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js